### ISSUE TITLE
Error: version_manager_version_string_not_found: Unable to find version string for blockchain time 1745995.

### ISSUE THREAD

**Issue by mahoekst** [decentralized-identity/ion#100]
Try to install ION network on my machine. The nodes seem all the be running and operating. On the ion-core node I keep seeing this error message in the log:

Waiting for 60 seconds before fetching and processing transactions again.

Refreshing cached blockchain time...
Refreshed blockchain time: {"time":1774301,"hash":"0000000000000005e4d5ff139bf724c9e506273dec8ea7a31dfa76c640f82f6a"}
Fetching Sidetree transactions from blockchain service...
Fetching URI 'http://ion-bitcoin:3002/transactions'...
Fetch response: 200'.
Fetched 13 Sidetree transactions from blockchain service in 4991 ms.
Waiting for 60 seconds before fetching and processing transactions again.
Encountered unhandled and possibly fatal Observer error, must investigate and fix:
{ Error: version_manager_version_string_not_found: Unable to find version string for blockchain time 1745995.
at VersionManager.getVersionString (/ion/node_modules/@decentralized-identity/sidetree/dist/lib/core/VersionManager.js:138:15)
at VersionManager.getTransactionSelector (/ion/node_modules/@decentralized-identity/sidetree/dist/lib/core/VersionManager.js:121:30)
at ThroughputLimiter.<anonymous> (/ion/node_modules/@decentralized-identity/sidetree/dist/lib/core/ThroughputLimiter.js:36:65)
at Generator.next (<anonymous>)
at /ion/node_modules/@decentralized-identity/sidetree/dist/lib/core/ThroughputLimiter.js:7:71
at new Promise (<anonymous>)
at __awaiter (/ion/node_modules/@decentralized-identity/sidetree/dist/lib/core/ThroughputLimiter.js:3:12)
at ThroughputLimiter.getQualifiedTransactions (/ion/node_modules/@decentralized-identity/sidetree/dist/lib/core/ThroughputLimiter.js:23:16)
at Observer.<anonymous> (/ion/node_modules/@decentralized-identity/sidetree/dist/lib/core/Observer.js:97:78)
at Generator.next (<anonymous>) code: 'version_manager_version_string_not_found' }

http://localhost:3000 returns this:
[
{
"name": "core",
"version": "0.9.1"
},
{
"name": "bitcoin",
"version": "0.9.1"
},
{
"name": "ipfs",
"version": "0.9.1"
}
]

**Comment by thehenrytsai** [comment]
This is no longer an issue since release of v1.
