### ISSUE TITLE
node install on Win10

### ISSUE THREAD

**Issue by ossobucco** [decentralized-identity/ion#148]
Hi,
Following the ion install-guide.md to create a mainnet node on a new & clean Win10 install, I get warnings when I run the 'npm i' command (please see first block below).
When I run 'npm run bitcoin', I get what appears to be a showstopping syntax error: 'Unexpected token U in JSON at position 33' (please see 2nd block below).
When I run 'npm run core', I get ECONNREFUSED 127.0.0.1:3002 (please see 3rd block below).  I imagine this is because the previous command errored out.

What does token U at position 33 mean?  The 33rd character in the testnet-bitcoin-config.json file (please see 4th block below)?
How should I best proceed in troubleshooting?  Thanks.

```
C:\Users\Second\ion>npm i
npm WARN markdown-it-attrs@3.0.1 requires a peer of markdown-it@^9.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN tslint-eslint-rules@5.4.0 requires a peer of tslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

audited 936 packages in 47.269s

16 packages are looking for funding
  run `npm fund` for details

found 1 high severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
```
```
C:\Users\Second\ion>npm run bitcoin
> ion@1.0.0 bitcoin C:\Users\Second\ion
> node dist/src/bitcoin.js

Environment variable ION_BITCOIN_CONFIG_FILE_PATH undefined, using default path ../json/testnet-bitcoin-config.json instead.
Environment variable ION_BITCOIN_VERSIONING_CONFIG_FILE_PATH undefined, using default ION bitcoin versioning config path ../json/testnet-bitcoin-versioning.json instead.
internal/modules/cjs/loader.js:1109
    throw err;
    ^

SyntaxError: C:\Users\Second\ion\dist\json\testnet-bitcoin-config.json: Unexpected token U in JSON at position 33
    at parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:1106:22)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\Second\ion\dist\src\bitcoin.js:78:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ion@1.0.0 bitcoin: `node dist/src/bitcoin.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ion@1.0.0 bitcoin script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Second\AppData\Roaming\npm-cache\_logs\2021-02-05T00_02_52_535Z-debug.log
```
```

C:\Users\Second\ion>npm run core

> ion@1.0.0 core C:\Users\Second\ion
> node dist/src/core.js

Environment variable ION_CORE_CONFIG_FILE_PATH undefined, using default core config path ../json/testnet-core-config.json instead.
Environment variable ION_CORE_VERSIONING_CONFIG_FILE_PATH undefined, using default core versioning config path ../json/testnet-core-versioning.json instead.
(node:7248) Warning: Accessing non-existent property 'count' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:7248) Warning: Accessing non-existent property 'findOne' of module exports inside circular dependency
(node:7248) Warning: Accessing non-existent property 'remove' of module exports inside circular dependency
(node:7248) Warning: Accessing non-existent property 'updateOne' of module exports inside circular dependency
Collection 'service' found.
Transaction collection already exists.
Unresolvable transaction collection already exists.
(node:7248) DeprecationWarning: collection.find option [fields] is deprecated and will be removed in a later version.
(node:7248) DeprecationWarning: collection.find option [fields] is deprecated and will be removed in a later version.
Refreshing cached blockchain time...
Sidetree node initialization failed with error FetchError: request to http://localhost:3002/time failed, reason: connect ECONNREFUSED 127.0.0.1:3002
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ion@1.0.0 core: `node dist/src/core.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ion@1.0.0 core script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Second\AppData\Roaming\npm-cache\_logs\2021-02-05T01_26_19_584Z-debug.log
```
```
{
  "bitcoinDataDirectory": "C:\Users\Second\AppData\Roaming\Bitcoin",
  "bitcoinFeeSpendingCutoffPeriodInBlocks": 1,
  "bitcoinFeeSpendingCutoff": 0.001,
  "bitcoinPeerUri": "http://localhost:8332",
  "bitcoinRpcUsername": "didion",
  "bitcoinRpcPassword": "lightning9times",
  "bitcoinWalletOrImportString": "KyVH3HoBatQWbEvgWaJhL8G9KquPYtRCK7uc1eDeP8V5UhsAZiTV",
  "databaseName": "ion-mainnet-bitcoin",
  "genesisBlockNumber": 667000,
  "logRequestError": true,
  "mongoDbConnectionString": "mongodb://localhost:27017/",
  "port": 3002,
  "sidetreeTransactionFeeMarkupPercentage": 1,
  "sidetreeTransactionPrefix": "ion:",
  "transactionPollPeriodInSeconds": 60,
  "valueTimeLockUpdateEnabled": false,
  "valueTimeLockAmountInBitcoins": 0,
  "valueTimeLockPollPeriodInSeconds": 600,
  "valueTimeLockTransactionFeesAmountInBitcoins": 0.0001
}
```

**Comment by thehenrytsai** [comment]
Hi @ossobucco.

Thanks for trying out ION! I am pretty sure the error is complaining about this line:

```
  "bitcoinDataDirectory": "C:\Users\Second\AppData\Roaming\Bitcoin",
```

You'll want to use forward slashes even though you are in Windows, like so:

```
  "bitcoinDataDirectory": "f:/Bitcoin/data",
```

**Comment by ossobucco** [comment]
Hi thehenrytsai,
That was it - thanks!
