### ISSUE TITLE
Unable to find version string for block 667000

### ISSUE THREAD

**Issue by mburns** [decentralized-identity/ion#149]
I'm running on Ubuntu 20.04 and configured everything for mainnet. The `ion-bitcoin` service seems to crash every few (~4) minutes with `Unable to find version string for block 667000`.

This seems to happen frequently enough that the `ion` service can never hit the `ion-bitcoin` endpoint successfully and come online.

There are other `Sidetree transaction found;` lines that it handles fine, fwiw.

Error:
```
Feb 08 07:01:33 ion-packet-sjc-001 ion_bitcoin[1151260]: Sidetree-Bitcoin node initialization failed with error: {"stack":"Error: Unable to find version string for block 667000.\n    at VersionManager.getVersionString (/usr/local/src/ion/node_modules/@decentralized-identity/sidetree/dist/lib/bitcoin/VersionManager.js:71:15)\n    at VersionManager.getFeeCalculator (/usr/local/src/ion/node_modules/@decentralized-identity/sidetree/dist/lib/bitcoin/VersionManager.js:49:30)\n    at BitcoinProcessor.<anonymous> (/usr/local/src/ion/node_modules/@decentralized-identity/sidetree/dist/lib/bitcoin/BitcoinProcessor.js:418:65)\n    at Generator.next (<anonymous>)\n    at /usr/local/src/ion/node_modules/@decentralized-identity/sidetree/dist/lib/bitcoin/BitcoinProcessor.js:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (/usr/local/src/ion/node_modules/@decentralized-identity/sidetree/dist/lib/bitcoin/BitcoinProcessor.js:4:12)\n    at BitcoinProcessor.writeBlocksToMetadataStoreWithFee (/usr/local/src/ion/node_modules/@decentralized-identity/sidetree/dist/lib/bitcoin/BitcoinProcessor.js:415:16)\n    at BitcoinProcessor.<anonymous> (/usr/local/src/ion/node_modules/@decentralized-identity/sidetree/dist/lib/bitcoin/BitcoinProcessor.js:158:24)\n    at Generator.next (<anonymous>)","message":"Unable to find version string for block 667000.","code":"version_manager_version_string_not_found"}
Feb 08 07:01:33 ion-packet-sjc-001 ion_bitcoin[1151229]: npm ERR! code ELIFECYCLE
Feb 08 07:01:33 ion-packet-sjc-001 ion_bitcoin[1151229]: npm ERR! errno 1
Feb 08 07:01:33 ion-packet-sjc-001 ion_bitcoin[1151229]: npm ERR! ion@1.0.1 bitcoin: `node dist/src/bitcoin.js`
Feb 08 07:01:33 ion-packet-sjc-001 ion_bitcoin[1151229]: npm ERR! Exit status 1
```

Tracking reboots from journald messages:
```
root@ion-packet-sjc-001:/usr/local/src/ion# journalctl -xe -t ion_bitcoin | grep 'Starting '
Feb 08 06:45:53 ion-packet-sjc-001 ion_bitcoin[1144486]: Starting block: 667000 (0000000000000000000bfc4add1faa645bed3add5486882966c13b29b0e82cdd)
Feb 08 06:49:51 ion-packet-sjc-001 ion_bitcoin[1146733]: Starting block: 667000 (0000000000000000000bfc4add1faa645bed3add5486882966c13b29b0e82cdd)
Feb 08 06:53:48 ion-packet-sjc-001 ion_bitcoin[1149035]: Starting block: 667000 (0000000000000000000bfc4add1faa645bed3add5486882966c13b29b0e82cdd)
Feb 08 06:57:47 ion-packet-sjc-001 ion_bitcoin[1151260]: Starting block: 667000 (0000000000000000000bfc4add1faa645bed3add5486882966c13b29b0e82cdd)
Feb 08 07:01:44 ion-packet-sjc-001 ion_bitcoin[1153486]: Starting block: 667000 (0000000000000000000bfc4add1faa645bed3add5486882966c13b29b0e82cdd)
Feb 08 07:05:41 ion-packet-sjc-001 ion_bitcoin[1155713]: Starting block: 667000 (0000000000000000000bfc4add1faa645bed3add5486882966c13b29b0e82cdd)
Feb 08 07:09:45 ion-packet-sjc-001 ion_bitcoin[1158034]: Starting block: 667000 (0000000000000000000bfc4add1faa645bed3add5486882966c13b29b0e82cdd)
Feb 08 07:13:45 ion-packet-sjc-001 ion_bitcoin[1160372]: Starting block: 667000 (0000000000000000000bfc4add1faa645bed3add5486882966c13b29b0e82cdd)
```

**Comment by isaacJChen** [comment]
667000 is the genesis block for v1. 
If you're seeing the mainnet path logged in here `Loading ION bitcoin versioning config from <your mainnet file>`... it should work. Can you check the file that shows up in that line of log? It should look like this

![image](https://user-images.githubusercontent.com/26752423/107261195-df582f80-69f3-11eb-94c9-bf27c95ca75d.png)

**Comment by mburns** [comment]
Thanks for the context, this was my problem.

I summarized how I shot myself in the foot here in case it is useful: https://github.com/decentralized-identity/ion/issues/75#issuecomment-775411641
