### ISSUE TITLE
Out of range error when parsing blocks

### ISSUE THREAD

**Issue by lemoustachiste** [decentralized-identity/ion#209]
Hi again,

I have managed to configure ION so that it would start retrieving data, but I am now facing a different issue.
Here is a curated copy of the ouput:
```
Sending jRPC request: id: 61nk1fj816v, method: getaddressinfo
Wallet found.
Locks collection does not exists, creating...
Locks collection created.
(node:44569) DeprecationWarning: collection.find option [fields] is deprecated and will be removed in a later version.
(node:44569) DeprecationWarning: collection.find option [fields] is deprecated and will be removed in a later version.
Upgrading DB from version undefined to 1.0.0...
DB upgraded in: 3 ms.
Trimming all block and transaction data after block height: undefined
Getting hash for block 1900000
Sending jRPC request: id: ekkdj902ok, method: getblockhash
Sending jRPC request: id: 718hp5pe0o5, method: getblockheader
Synchronizing blocks for sidetree transactions...
Starting block: 1900000 (000000000000000eda80f8c7e55459e348274292ecd77c662f95e29bedbb4865)
Getting current block height...
Sending jRPC request: id: 538mc9ii8cd, method: getblockcount
Getting hash for block 2005758
Sending jRPC request: id: 4m2u4qgb44f, method: getblockhash
Sending jRPC request: id: 7jmu8oripkb, method: getblockheader
Begin fast processing block 1900000 to 2005758
Parsing file: blk00198.dat
Finished processing 1171 blocks from raw block file
Sending jRPC request: id: urpclbdg0, method: getrawtransaction
Sending jRPC request: id: 2f0uvnh3ab6, method: getrawtransaction
Sending jRPC request: id: 3g41r7v8ho8, method: getrawtransaction
Sidetree transaction found; adding {"transactionNumber":8607797360984094,"transactionTime":2004159,"transactionTimeHash":"00000000c705fbbc6bd7890b0a94331b27e6eb1611835743783a0819691f436d","anchorString":"6.QmQGEyLj3W9QB5qnGYLYaskkPMEweTwXVN3XsfziKu42so","transactionFeePaid":911,"writer":"395eb64155351b47dad51bc8da3675b1231b18d4"}
[...]
Parsing file: blk00004.dat
Finished processing 1304 blocks from raw block file
Found 0 valid blocks.
Parsing file: blk00003.dat
Finished processing 3494 blocks from raw block file
Found 0 valid blocks.
Parsing file: blk00002.dat
Finished processing 62435 blocks from raw block file
Found 0 valid blocks.
Parsing file: blk00001.dat
Finished processing 53852 blocks from raw block file
Found 0 valid blocks.
Parsing file: blk00000.dat
Sidetree-Bitcoin node initialization failed with error: {"stack":"RangeError [ERR_OUT_OF_RANGE]: The value of \"byteLength\" is out of range. It must be >= 1 and <= 6. Received 105\n    at boundsError (internal/buffer.js:77:9)\n    at Buffer.readUIntLE (internal/buffer.js:175:3)\n    at Function.getBlockHeightFromBlock (/Users/julien/work/ion/node_modules/@decentralized-identity/sidetree/dist/lib/bitcoin/BitcoinRawDataParser.js:77:47)\n    at Function.parseRawDataFile (/Users/julien/work/ion/node_modules/@decentralized-identity/sidetree/dist/lib/bitcoin/BitcoinRawDataParser.js:50:54)\n    at BitcoinBlockDataIterator.previous (/Users/julien/work/ion/node_modules/@decentralized-identity/sidetree/dist/lib/bitcoin/BitcoinBlockDataIterator.js:30:59)\n    at BitcoinProcessor.<anonymous> (/Users/julien/work/ion/node_modules/@decentralized-identity/sidetree/dist/lib/bitcoin/BitcoinProcessor.js:151:57)\n    at Generator.next (<anonymous>)\n    at fulfilled (/Users/julien/work/ion/node_modules/@decentralized-identity/sidetree/dist/lib/bitcoin/BitcoinProcessor.js:5:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)","message":"The value of \"byteLength\" is out of range. It must be >= 1 and <= 6. Received 105","code":"ERR_OUT_OF_RANGE"}
```

I have ran this process three times and three times it failed with the error above.

I couldn't find a similar issue neither on Sidetree's repo nor here. I don't understand what's happening here.

Thanks for your help

**Comment by lemoustachiste** [comment]
It looks like it's coming from the blocks

this are the last 2 blocks being parsed, as read from this method https://github.com/decentralized-identity/sidetree/blob/master/lib/bitcoin/BitcoinRawDataParser.ts#L88:

```
Input {
  prevTxId: <Buffer 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>,
  outputIndex: 4294967295,
  _scriptBuffer: <Buffer 04 da aa 4a 4d 02 4a 01 06 2f 50 32 53 48 2f>,
  sequenceNumber: 4294967295
}
04daaa4a4d024a01062f503253482f 30
4
----
Input {
  prevTxId: <Buffer 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>,
  outputIndex: 4294967295,
  _scriptBuffer: <Buffer 69 d6 14 f5 f6 9b ab 70 45 52 e6 6e ea f7 20 d0 72 94 eb e8 0b a3 71 81 a5 df 8c 7f da ec ac 91 08 78 06 0b 0a 85 54 3d e9 b2 24>,
  sequenceNumber: 4294967295
}
69d614f5f69bab704552e66eeaf720d07294ebe80ba37181a5df8c7fdaecac910878060b0a85543de9b224 86
105
```

Here is what's being output:
```
console.log(block.transactions[0].inputs[0]);
// the first transaction, the coinbase, contains the block height in its input
const coinbaseInputScript = block.transactions[0].inputs[0]._scriptBuffer;
console.log(coinbaseInputScript.toString('hex'), coinbaseInputScript.toString('hex').length);
// this denotes how many bytes following represent the block height
let heightBytes = coinbaseInputScript.readUInt8(0);
console.log(heightBytes);
```

So the last buffer is longer than the others.
I have synced with testnet chain from bitcoin-core.

So this is the block data:
```
{
  "header": {
    "hash": "0000000077287b8e0283c0658bfa6b82d5d3656b52d52532b224786fc9fcf981",
    "version": 1,
    "prevHash": "00000000520db768abcf70d0580a98ed99ea65efece97b815c3b63dba1f91b0a",
    "merkleRoot": "d5aba131a88c92926bf4db65e5eb83ec2c6ace9f3587a5695351c0ea44a8fcc9",
    "time": 1296740938,
    "bits": 486604799,
    "nonce": 1609986051
  },
  "transactions": [
    {
      "hash": "d5aba131a88c92926bf4db65e5eb83ec2c6ace9f3587a5695351c0ea44a8fcc9",
      "version": 1,
      "inputs": [
        {
          "prevTxId": "0000000000000000000000000000000000000000000000000000000000000000",
          "outputIndex": 4294967295,
          "sequenceNumber": 4294967295,
          "script": "69d614f5f69bab704552e66eeaf720d07294ebe80ba37181a5df8c7fdaecac910878060b0a85543de9b224"
        }
      ],
      "outputs": [
        {
          "satoshis": 5000000000,
          "script": "2102f3cedb3c71052860e6329e4fd7b1ad51220a21111f2bf4fec3691e6f52664a75ac"
        }
      ],
      "nLockTime": 0
    }
  ]
}
```

As found here: https://live.blockcypher.com/btc-testnet/block/0000000077287b8e0283c0658bfa6b82d5d3656b52d52532b224786fc9fcf981/

not sure if that helps, I am generally speaking new in the internals of the blockchain

**Comment by thehenrytsai** [comment]
@lemoustachiste, your log shows that the ION node processed from the end of the blockchain all the way to the testnet genesis (`blk00198.dat` to `blk00000.dat`), this is NOT supposed to happen, it is supposed process backward from end of the chai and stop as soon as it processed the file containing block 1900000, which is ION's genesis block.

Not sure if you are able locate the file containing block 1900000 and share with us? I will look into code for a bug that prevents the code from completing the fast initial sync once it reaches block 1900000. Meanwhile, you can try to turn off fast sync by setting `bitcoinDataDirectory` in bitcoin service config, this will go through the "normal/slow sync code path" using RPC calls.

**Comment by lemoustachiste** [comment]
So to unstuck me I changed this line: https://github.com/decentralized-identity/sidetree/blob/master/lib/bitcoin/BitcoinBlockDataIterator.ts#L23 to not parse the last block. It seems now that ION node is running when `npm run bitcoin` and does not go through parsing anymore. How do I reset that?

> Not sure if you are able locate the file containing block 1900000 and share with us?

Sorry I didn't get that clearly, do you want the file or just the block content? That's related to the point above too to start a new parsing.

Here is my current output:
```
Sidetree transaction found; adding {"transactionNumber":8615828949827608,"transactionTime":2006029,"transactionTimeHash":"00000000000000267b32122af99b2234377e962bd2b43143475a4fd119840ad7","anchorString":"3.QmZcsecuTZ8TNxJrLvQwsUPLppAmoApdYz9Ne3kHjeLHZQ","transactionFeePaid":928,"writer":"395eb64155351b47dad51bc8da3675b1231b18d4"}
Sending jRPC request: id: 6q6hm8sbe7b, method: getrawtransaction
Sending jRPC request: id: 5rmkne4n74b, method: getrawtransaction
Sending jRPC request: id: 29s2j51gt9k, method: getrawtransaction
Sidetree transaction found; adding {"transactionNumber":8615828949827609,"transactionTime":2006029,"transactionTimeHash":"00000000000000267b32122af99b2234377e962bd2b43143475a4fd119840ad7","anchorString":"2.QmNo6pNwoGG3devLc5x75VJLfuXckcRPbP2benZ7DV3dqv","transactionFeePaid":929,"writer":"7628046f6ec479c031d03a47b6a003c4dedb1cad"}
Sending jRPC request: id: 31ddgicv91a, method: getrawtransaction
Sending jRPC request: id: 7hi1or4dq55, method: getrawtransaction
Sending jRPC request: id: 2but8rc60io, method: getrawtransaction
Sidetree transaction found; adding {"transactionNumber":8615828949827610,"transactionTime":2006029,"transactionTimeHash":"00000000000000267b32122af99b2234377e962bd2b43143475a4fd119840ad7","anchorString":"3.QmQSn11EEnjwho3GKvwegRbZqHiAtSL3PkSA7QBYCVSvWh","transactionFeePaid":929,"writer":"7628046f6ec479c031d03a47b6a003c4dedb1cad"}
Calculated raw normalized fee for block 2006029: 919.4717272790449
Finished processing blocks 2006029 to 2006029
Event emitted: bitcoin_observing_loop_success
``` 
I assume this is the correct state of things?

**Comment by thehenrytsai** [comment]
> How do I reset that?

Initial fast sync only occurs once, normal sync via RPC calls kicks in after. To resync everything again, delete the `ion-testnet-bitcoin` DB.

>  do you want the file or just the block content?

I actually want the file, since block 1900000 content should be the same regardless of nodes, but the file will be different for every node since blocks are downloaded at different speed. I suspect it is the file parsing logic that is not handling some edge conditions. I understand it might be hard since it's ~130MB in size, so you'll probably have to share a temporary file link.

> I assume this is the correct state of things?

This is the correct state of things assuming there was no ION transaction(s) in the last block of every block file (since you remove the parsing of the last block). For testnet purposes, it's probably okay, but would definitely love to get a repro to fix the actual issue you saw.

**Comment by lemoustachiste** [comment]
Hi @thehenrytsai,

here is the block file: blk00000.dat, I assume this is where block 1900000 is: https://drive.google.com/file/d/1dWTL9sWa9vwN0jf-QY1etvb8Ri1v9ehS/view?usp=sharing

> delete the ion-testnet-bitcoin DB.

at mongodb level, correct? 

For now I have managed to get a did anchored so I think I will avoid going down that route again as I have what I need to pursue my purpose.

Is there a preferred place for feedback? I have noticed some small items during my setup and dev process, but I am not sure if spamming with issues is the correct approach for that?

**Comment by thehenrytsai** [comment]
@lemoustachiste, thanks for going out of your way to provide us the file, we will download it and debug.

> at mongodb level, correct?

Yes.

> Is there a preferred place for feedback?

Opening issues is the way to go, not spamming at all. Just make sure you create separate issues so we can address them individually.

**Comment by thehenrytsai** [comment]
@lemoustachiste, I attempted to debug using the file you gave us and printed out the block numbers that are parsed from the file before the problematic block is hit, and they are WAY larger than what one would expect from testnet:

 e.g.
```
...
1296737859
1296737973
1296738150
1296738394
1296738614
1296738439
1296738618
1296738606
1296738711
1296739034 <- the block before the failure in parsing the next block
```

Are you sure you are testing against testnet? Because the tip of the testnet blockchain have just currently past 2000000, so the height you are getting is WAY larger. This would explain why the code keeps processing all the way until the first block file. Something isn't adding up here, maybe you are using some configuration that we are not aware of. Are you using Bitcoin Core client?

**Comment by lemoustachiste** [comment]
Thanks for your feedback, I have initially synced with Bitcoin core client yes. It took about 2 hours so I didn't notice anything out of the expected there. It was quite a black box since all by GUI. But I had an initial round of synchronization with the mainnet network, though it's not in the same directory.

After that since I didn't like being in the dark I went on to manually install bitcoin core items (namely bitcoin-cli and bitcoind), but I don't think it had to sync since I was pointing the testnet3/blocks folder already. Things have been working correctly apart from the error reported here. 

I am sorry I cannot help more than that. If you think that's a one off then I am not against closing this issue. I was able to move forward with the hacky solution so as far as I am concerned I am not stuck.

**Comment by thehenrytsai** [comment]
@lemoustachiste, thanks for the info. Are you able to help with one last thing: pasting the latest logs from the ION bitcoin service?

It should look something like:

```
Sending jRPC request: id: 3jp5oh4stj8, method: getblockcount
Getting hash for block 688798
Sending jRPC request: id: va67flntr6, method: getblockhash
Retrieved block 688798 (00000000000000000006aa65ca7a60d7827d6397090159938d402b64a93c7526)
Returning transactions since block 688798...
Verifying block 688807 (00000000000000000004f23e94c13cba343b3390404def1b0a34f81eb653dad7)
Getting current block height...
Sending jRPC request: id: 1flna8cqhq8, method: getblockcount
Getting hash for block 688807
Sending jRPC request: id: f1pt7vp3gs, method: getblockhash
Retrieved block 688807 (00000000000000000004f23e94c13cba343b3390404def1b0a34f81eb653dad7)
Getting time
Verifying block 688807 (00000000000000000004f23e94c13cba343b3390404def1b0a34f81eb653dad7)
Getting current block height...
Sending jRPC request: id: 968v568o1u, method: getblockcount
Getting hash for block 688807
Sending jRPC request: id: 198eq5tvv6q, method: getblockhash
Retrieved block 688807 (00000000000000000004f23e94c13cba343b3390404def1b0a34f81eb653dad7)
Trimming all block and transaction data after block height: 688807
```

I am basically looking for the block height that the ION node is reporting, in the log I pasted, it shows `688807` because this ION node is running against `mainnet`.

**Comment by lemoustachiste** [comment]
This is what I have at this moment

```
Verifying block 2006315 (0000000000000013643377a58a0e961713d00fff2e663d44906d03ac6e08925b)
Getting current block height...
Sending jRPC request: id: 6pa2obc174n, method: getblockcount
Getting hash for block 2006315
Sending jRPC request: id: 6b424sc8q8l, method: getblockhash
Retrieved block 2006315 (0000000000000013643377a58a0e961713d00fff2e663d44906d03ac6e08925b)
Returning transactions since block 2006315...
Verifying block 2006317 (000000000000000cbc90df13be832f92e38bac17f9c5a4fd75205f203292fb1d)
Getting current block height...
Sending jRPC request: id: 7gkoksbb1jd, method: getblockcount
Getting hash for block 2006317
Sending jRPC request: id: 1ki8t1sa8fo, method: getblockhash
Retrieved block 2006317 (000000000000000cbc90df13be832f92e38bac17f9c5a4fd75205f203292fb1d)
```

**Comment by thehenrytsai** [comment]
@lemoustachiste, thanks, we will take it from here. Will leave this issue open for a couple of weeks to see if anyone has more input on parsing block files.

**Comment by isaacJChen** [comment]
@lemoustachiste Are you able to upload all your blk files or full log? It appears that your ION node went past block 1900000 and continued processing possibly due to some bug. I am unable to repro it as everyone's blk files are structured differently. Thank you so much! :)

**Comment by lemoustachiste** [comment]
@isaacJChen there is 26.62GB of data. Would you have an endpoint where I can upload that? Otherwise I'll check with the SREs if they can provide me with a space somewhere.

**Comment by isaacJChen** [comment]
Actually, I think genesis block should be in the first few files. I just want to see if I am able to get to genesis block with your blk files. Are you able to upload the 15 latest blk files you have? So should be blk00180 to blk00198 ish. I was able to reach genesis block in those files, and I expect other nodes to be the same. If it's still too big, feel free to zip them. Alternatively you can email me if you aren't able to upload it. Thanks!
