### ISSUE TITLE
npm ERR! code ELIFECYCLE / npm ERR! ion@1.0.2 bitcoin: `node dist/src/bitcoin.js`

### ISSUE THREAD

**Issue by odontesthes** [decentralized-identity/ion#219]
Good afternoon,
Without first greeting you and thanking you in advance for your time and help, I comment on a university project I am getting started on the subject, and testing ION (in Windows 10), but in particular in the next step:
************************************************************
6. Run ION Bitcoin microservice
Update the paths below to where you editted and saved the config files from the previous step.
ION_BITCOIN_CONFIG_FILE_PATH=/etc/ion/testnet-bitcoin-config.json
ION_BITCOIN_VERSIONING_CONFIG_FILE_PATH=/etc/ion/testnet-bitcoin-versioning.json
npm run bitcoin
************************************************************
- The system responds to me with the following error:
C:\ion>npm run bitcoin
> ion@1.0.2 bitcoin C:\ion
> node dist/src/bitcoin.js
Environment variable ION_BITCOIN_CONFIG_FILE_PATH undefined, using default path ../json/testnet-bitcoin-config.json instead.
Environment variable ION_BITCOIN_VERSIONING_CONFIG_FILE_PATH undefined, using default ION bitcoin versioning config path ../json/testnet-bitcoin-versioning.json instead.
internal/modules/cjs/loader.js:1109
    throw err;
    ^
SyntaxError: C:\ion\dist\json\testnet-bitcoin-config.json: Unexpected token U in JSON at position 33
    at parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:1106:22)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\ion\dist\src\bitcoin.js:78:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ion@1.0.2 bitcoin: `node dist/src/bitcoin.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ion@1.0.2 bitcoin script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Consultor\AppData\Roaming\npm-cache\_logs\2021-07-20T04_01_17_767Z-debug.log

**********************************************
Log:
**********************************************
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'bitcoin'
1 verbose cli ]
2 info using npm@6.14.11
3 info using node@v14.16.0
4 verbose run-script [ 'prebitcoin', 'bitcoin', 'postbitcoin' ]
5 info lifecycle ion@1.0.2~prebitcoin: ion@1.0.2
6 info lifecycle ion@1.0.2~bitcoin: ion@1.0.2
7 verbose lifecycle ion@1.0.2~bitcoin: unsafe-perm in lifecycle true
8 verbose lifecycle ion@1.0.2~bitcoin: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\ion\node_modules\.bin;C:\Program Files\Python37\Scripts\;C:\Program Files\Python37\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Program Files\MySQL\MySQL Shell 8.0\bin\;C:\Users\Consultor\AppData\Local\Microsoft\WindowsApps;;C:\Users\Consultor\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\Consultor\AppData\Roaming\npm;C:\Users\Consultor\AppData\Local\Programs\IPFS Desktop\resources\app.asar.unpacked\src\ipfs-on-path\scripts\bin-win
9 verbose lifecycle ion@1.0.2~bitcoin: CWD: C:\ion
10 silly lifecycle ion@1.0.2~bitcoin: Args: [ '/d /s /c', 'node dist/src/bitcoin.js' ]
11 silly lifecycle ion@1.0.2~bitcoin: Returned: code: 1  signal: null
12 info lifecycle ion@1.0.2~bitcoin: Failed to exec bitcoin script
13 verbose stack Error: ion@1.0.2 bitcoin: `node dist/src/bitcoin.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1048:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid ion@1.0.2
15 verbose cwd C:\ion
16 verbose Windows_NT 10.0.19043
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "bitcoin"
18 verbose node v14.16.0
19 verbose npm  v6.14.11
20 error code ELIFECYCLE
21 error errno 1
22 error ion@1.0.2 bitcoin: `node dist/src/bitcoin.js`
22 error Exit status 1
23 error Failed at the ion@1.0.2 bitcoin script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
**************************************************
Can you please guide me to solve the problem?
I thank you in advance for your attention and time,
Best regards,
Juan

**Comment by odontesthes** [comment]
Dear,
Regarding the previous error I could solve it.
The problem was in the file "testnet-bitcoin-config.json"
In particular in "Bitcoindatadirectory" had to change the character of "\" to the "/" character, according to example indicated (using Win10)
"Bitcoindatadirectory": "C: / Users / Consultant / AppData / Roaming / Bitcoin / TestNet3",
regards
John
