### ISSUE TITLE
npm run core: "connect ECONNREFUSED 127.0.0.1:3002"

### ISSUE THREAD

**Issue by Busch** [decentralized-identity/ion#252]
Hello Community,

When I run core, I receive the following error:

```
S:\ION\ion>npm run core

> ion@1.0.3 core S:\ION\ion
> node dist/src/core.js

Loading core config from S:\ION\mainnet-core-config.json...
Loading core versioning config from S:\ION\mainnet-core-versioning.json...
(node:3592) Warning: Accessing non-existent property 'MongoError' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:3592) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
Collection 'service' found.
Transaction collection already exists.
Unresolvable transaction collection already exists.
Collection 'operations' found.
(node:3592) DeprecationWarning: collection.find option [fields] is deprecated and will be removed in a later version.
(node:3592) DeprecationWarning: collection.find option [fields] is deprecated and will be removed in a later version.
Starting periodic transactions processing.
Getting blockchain time...
Fetching Sidetree transactions from blockchain service...
Fetching URI 'http://localhost:3002/transactions'...
Error occurred while updating blockchain time, investigate and fix: FetchError: request to http://localhost:3002/time failed, reason: connect ECONNREFUSED 127.0.0.1:3002
Core cachedApproximateTime updated to: undefined
Event emitted: sidetree_observer_loop_failure
Encountered unhandled and possibly fatal Observer error, must investigate and fix:
FetchError: request to http://localhost:3002/transactions failed, reason: connect ECONNREFUSED 127.0.0.1:3002
    at ClientRequest.<anonymous> (S:\ION\ion\node_modules\node-fetch\lib\index.js:1461:11)
    at ClientRequest.emit (events.js:400:28)
    at Socket.socketErrorListener (_http_client.js:475:9)
    at Socket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED'
}
Waiting for 60 seconds before fetching and processing transactions again.
Start operation batch writing...
Getting blockchain time...
Unexpected and unhandled error during batch writing, investigate and fix:
FetchError: request to http://localhost:3002/time failed, reason: connect ECONNREFUSED 127.0.0.1:3002
    at ClientRequest.<anonymous> (S:\ION\ion\node_modules\node-fetch\lib\index.js:1461:11)
    at ClientRequest.emit (events.js:400:28)
    at Socket.socketErrorListener (_http_client.js:475:9)
    at Socket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED'
}
```

I can confirm that the bitcoin service is running and is finding transactions. However, when I check using netstat, no service is listening on port 3002.

```
S:\ION\ion>npm run bitcoin

> ion@1.0.3 bitcoin S:\ION\ion
> node dist/src/bitcoin.js

Loading configuration from S:\ION\mainnet-bitcoin-config.json...
Loading ION bitcoin versioning config from S:\ION\mainnet-bitcoin-versioning.json...
Creating bitcoin wallet using the import string passed in.
Sidetree bitcoin service configuration:
(node:6548) Warning: Accessing non-existent property 'MongoError' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:6548) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
Collection 'service' found.
Collection 'blocks' found.
Transaction collection already exists.
Sending jRPC request: id: 6csekdnpvmr, method: createwallet
Wallet with name sidetreeDefaultWallet already exists.
Sending jRPC request: id: 5jr7ki4c49r, method: loadwallet
Wallet with name sidetreeDefaultWallet already loaded.
Checking if bitcoin contains a wallet for ***REDACTED***
Checking if bitcoin wallet for ***REDACTED*** exists
Sending jRPC request: id: 8toneva518, method: getaddressinfo
Wallet found.
Locks collection already exists.
(node:6548) DeprecationWarning: collection.find option [fields] is deprecated and will be removed in a later version.
(node:6548) DeprecationWarning: collection.find option [fields] is deprecated and will be removed in a later version.
Trimming all block and transaction data after block height: undefined
Getting hash for block 667000
Sending jRPC request: id: 6qfcfc56893, method: getblockhash
Request timeout (0)
Retrying request (1)
Sending jRPC request: id: 5esltfho279, method: getblockheader
Synchronizing blocks for sidetree transactions...
Starting block: 667000 (0000000000000000000bfc4add1faa645bed3add5486882966c13b29b0e82cdd)
Getting current block height...
Sending jRPC request: id: 5m180oaa5vl, method: getblockcount
Getting hash for block 698149
Sending jRPC request: id: 2kd919i2jbe, method: getblockhash
Sending jRPC request: id: 61qkf4eqiot, method: getblockheader
Begin fast processing block 667000 to 698149
Parsing file: blk02705.dat
Finished processing 142 blocks from raw block file
Sending jRPC request: id: 5qidg5sm7cp, method: getrawtransaction
Request timeout (0)
Retrying request (1)
Request timeout (1)
Retrying request (2)
Request timeout (2)
Retrying request (3)
Sending jRPC request: id: 1ap88a6656c, method: getrawtransaction
Sending jRPC request: id: 1m7tkkpj534, method: getrawtransaction
Sidetree transaction found; adding {"transactionNumber":2998230769991825,"transactionTime":698080,"transactionTimeHash":"0000000000000000000df47aee4881fcebc323b224cb7ac1d0988dc115c90f38","anchorString":"1.QmZuUmcp1JzrV9C9wnYRDLVqZLhcdKbhVJwbvhPNFP2aaj","transactionFeePaid":1377,"writer":"90dbe1e00414e6f31df235b005ee4da035076fbf"}
Sending jRPC request: id: 89lv2is0jc, method: getrawtransaction
Sending jRPC request: id: 1lq7k1ehu0i, method: getrawtransaction
Sending jRPC request: id: 4ulvhkcpmnd, method: getrawtransaction
Sidetree transaction found; adding {"transactionNumber":2998346734109028,"transactionTime":698107,"transactionTimeHash":"0000000000000000000360a7ed3355ddb8eb35c3e5fd5bc4e9b8acab8cd0cd54","anchorString":"7.QmfBKDvVRjMfe5x7j3sS52HsEgdDsVZukN1GVwe7QiAJFB","transactionFeePaid":1377,"writer":"90dbe1e00414e6f31df235b005ee4da035076fbf"}
[...]
```

This is my mainnet-bitcoin-config.json:

```
{
  "bitcoinDataDirectory": "S:\\ION\\bitcoin-data",
  "bitcoinFeeSpendingCutoffPeriodInBlocks": 1,
  "bitcoinFeeSpendingCutoff": 0.001,
  "bitcoinPeerUri": "http://localhost:8332",
  "bitcoinRpcUsername": "admin",
  "bitcoinRpcPassword": "***REDACTED***",
  "bitcoinWalletOrImportString": "***REDACTED***",
  "databaseName": "ion-mainnet-bitcoin",
  "genesisBlockNumber": 667000,
  "requestMaxRetries": 10,
  "logRequestError": true,
  "mongoDbConnectionString": "mongodb://localhost:27017/",
  "port": 3002,
  "sidetreeTransactionFeeMarkupPercentage": 1,
  "sidetreeTransactionPrefix": "ion:",
  "transactionPollPeriodInSeconds": 60,
  "valueTimeLockUpdateEnabled": false,
  "valueTimeLockAmountInBitcoins": 0,
  "valueTimeLockPollPeriodInSeconds": 600,
  "valueTimeLockTransactionFeesAmountInBitcoins": 0.0001
}
```

This is my mainnet-core-config.json:

```
{
  "batchingIntervalInSeconds": 600,
  "blockchainServiceUri": "http://localhost:3002",
  "databaseName": "ion-mainnet-core",
  "didMethodName": "ion",
  "ipfsHttpApiEndpointUri": "http://localhost:5001",
  "maxConcurrentDownloads": 20,
  "mongoDbConnectionString": "mongodb://localhost:27017/",
  "observingIntervalInSeconds": 60,
  "port": 3000
}
```

OS: Windows Server 2019

Any idea why there is no service listening on port 3002?

**Comment by Busch** [comment]
After a couple of hours of troubleshooting, I decided to take a look at the source code. I have seen that the bitcoin service starts AFTER all blocks are parsed:
```
blockchainService.initialize(ionBitcoinVersions)
    .then(() => {
      server = app.listen(port, () => {
        console.log(`Sidetree-Bitcoin node running on port: ${port}`);
      });
```

So I guess I only have to wait for a couple of days until all blocks are parsed. Hopefully the bitcoin service only parses blocks since the genesis block (667000) defined in the mainnet-bitcoin-config.json.

I will update this issue as soon as my crappy hardware is done parsing the remaining blocks.

**Comment by Busch** [comment]
Update:

Problem solved. 
I just had to wait until all block were parsed. This issue can me marked as resolved.
