### ISSUE TITLE
npm run bitcoin cannot start for testnet

### ISSUE THREAD

**Issue by ZhengkunWang** [decentralized-identity/ion#259]
hello, I'm trying to setup the ion node on my macbook pro a top of testnet, I ready started the mongo ipfs and bitcoind on my local, then I run `npm run bitcoin`, it will raise this error:
```
Creating bitcoin wallet using the import string passed in.
Sidetree bitcoin service configuration:
(node:1576) Warning: Accessing non-existent property 'MongoError' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1576) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
Collection 'service' found.
Collection 'blocks' found.
Transaction collection already exists.
Sending jRPC request: id: 6msn7cqmkn1, method: createwallet
Wallet with name sidetreeDefaultWallet already exists.
Sending jRPC request: id: 5hjtmuhajjr, method: loadwallet
Sidetree-Bitcoin node initialization failed with error: {"stack":"Error: Fetch failed [500]: {\"result\":null,\"error\":{\"code\":-4,\"message\":\"Wallet file verification failed. SQLiteDatabase: Unable to obtain an exclusive lock on the database, is it being used by another bitcoind?\\n\"},\"id\":\"5hjtmuhajjr\"}\n\n    at BitcoinClient.<anonymous> (/Users/zkwang/Project/ion/node_modules/@decentralized-identity/sidetree/dist/lib/bitcoin/BitcoinClient.js:755:31)\n    at Generator.next (<anonymous>)\n    at fulfilled (/Users/zkwang/Project/ion/node_modules/@decentralized-identity/sidetree/dist/lib/bitcoin/BitcoinClient.js:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","message":"Fetch failed [500]: {\"result\":null,\"error\":{\"code\":-4,\"message\":\"Wallet file verification failed. SQLiteDatabase: Unable to obtain an exclusive lock on the database, is it being used by another bitcoind?\\n\"},\"id\":\"5hjtmuhajjr\"}\n"}
```

**Comment by ZhengkunWang** [comment]
I figured this out by my self, I'm using the bitcoind v22, which the Ion v1.0.3 is targeted for bitcoind v0.21.0, so I switched back from v22 to v0.21.0, and it start to run.

**Comment by coffnix** [comment]
ion works on bitcoind v23.0 ?
