### ISSUE TITLE
Unable to submit an anchor request.

### ISSUE THREAD

**Issue by mingw-io** [decentralized-identity/ion#260]
Ciao.

First of all, I'm new new new to this project. First time playing with/learning/trying things out. Bear with me.

Everything seems to be set up properly (Windows 10 x64).

For example,

GET http://127.0.0.1:3000/version

[
    {
        "name": "core",
        "version": "1.0.5"
    },
    {
        "name": "bitcoin",
        "version": "1.0.5"
    }
]

GET http://127.0.0.1:3002/time

{
    "time": 101,
    "hash": "653c9252f6c1f44100f9c1a25808be47266417c421c256a6d837216da510985c"
}

When submitting a new anchor request, I get a runtime exception:

{"type":"create","suffixData":{"deltaHash":"EiAprCgGSbHIPheay29JPcBgU7jtOOHL6XqbdBcBlc2IWw","recoveryCommitment":"EiCkksH16Rr-Mn7b4Nnd4-nVTgOSMojpjT1YySVXJC2yTg"},"delta":{"updateCommitment":"EiAugU--IJpwfBzCMAbmMmg-NvjSJ8QTbxshiHDBEjmEWA","patches":[{"action":"replace","document":{"publicKeys":[{"id":"auth-key","type":"EcdsaSecp256k1VerificationKey2019","publicKeyJwk":{"kty":"EC","crv":"secp256k1","x":"FJT4rkP_5XWQzKVJ_AUhNpSC-84STdgUac6FfgOWJb0","y":"gu34Kg7wFCnq33GT2orj3UGB11GK5H_45lTsyaADUPA"},"purposes":["authentication"]}],"services":[{"id":"IdentityHub","type":"IdentityHub","serviceEndpoint":{"@context":"schema.identity.foundation/hub","@type":"UserServiceEndpoint","instance":["did:test:hub.id"]}}]}}]}}

Solving for body:
{"type":"create","suffixData":{"deltaHash":"EiAprCgGSbHIPheay29JPcBgU7jtOOHL6XqbdBcBlc2IWw","recoveryCommitment":"EiCkksH16Rr-Mn7b4Nnd4-nVTgOSMojpjT1YySVXJC2yTg"},"delta":{"updateCommitment":"EiAugU--IJpwfBzCMAbmMmg-NvjSJ8QTbxshiHDBEjmEWA","patches":[{"action":"replace","document":{"publicKeys":[{"id":"auth-key","type":"EcdsaSecp256k1VerificationKey2019","publicKeyJwk":{"kty":"EC","crv":"secp256k1","x":"FJT4rkP_5XWQzKVJ_AUhNpSC-84STdgUac6FfgOWJb0","y":"gu34Kg7wFCnq33GT2orj3UGB11GK5H_45lTsyaADUPA"},"purposes":["authentication"]}],"services":[{"id":"IdentityHub","type":"IdentityHub","serviceEndpoint":{"@context":"schema.identity.foundation/hub","@type":"UserServiceEndpoint","instance":["did:test:hub.id"]}}]}}]}}
C:\msys\1.0\src\ion-test-2022\node_modules\ion-pow-sdk\node_modules\buffer\index.js:123
    throw new TypeError(
          ^

TypeError: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type undefined
    at from (C:\msys\1.0\src\ion-test-2022\node_modules\ion-pow-sdk\node_modules\buffer\index.js:123:11)
    at Function.Buffer.from (C:\msys\1.0\src\ion-test-2022\node_modules\ion-pow-sdk\node_modules\buffer\index.js:174:10)
    at Function.submitIonRequest (C:\msys\1.0\src\ion-test-2022\node_modules\ion-pow-sdk\src\index.js:45:30)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async main (C:\msys\1.0\src\ion-test-2022\did.js:66:24)

Any pointers/assistance would be highly appreciated.

Thanks for this project.

Cheers.

**Comment by thehenrytsai** [comment]
@mingw-io, sorry for the late response. From the log it I can see that you are attempting to use `ion-pow-sdk` to submit your create request to your own node, this is a misunderstanding of `ion-pow-sdk`.

You do not need to use `ion-pow-sdk` at all when submitting requests to your own local ION node, you simply POST your requests to `http://localhost:3000/operations`, but you do need to however have BTC in your Bitcoin Core wallet, so that you can write bitcoin transactions of course.

`ion-pow-sdk` is currently written specifically to target [Microsoft's ION node](https://beta.ion.msidentity.com/api/v1.0/proof-of-work-challenge) which implements a proof-of-work scheme to prevent spam of ION operation requests.
