### ISSUE TITLE
ION transaction fetch failing

### ISSUE THREAD

**Issue by tplooker** [decentralized-identity/ion#99]
Running the current ION release 0.8.2 after sync, the following error occurs each time the ion node enquires about transactions.

```
Fetching URI 'http://ion-bitcoin:3002/transactions'...
ion-core        | No queued operations to batch.
ion-core        | End batch writing. Duration: 47 ms.
ion-core        | Waiting for 600 seconds before writing another batch.
ion-core        | Fetch response: 200'.
ion-core        | Fetched 13 Sidetree transactions from blockchain service in 4065 ms.
ion-core        | Encountered unhandled and possibly fatal Observer error, must investigate and fix:
ion-core        | Waiting for 60 seconds before fetching and processing transactions again.
ion-core        | { Error: version_manager_version_string_not_found: Unable to find version string for blockchain time 1745995.
ion-core        |     at VersionManager.getVersionString (/ion/node_modules/@decentralized-identity/sidetree/dist/lib/core/VersionManager.js:138:15)
ion-core        |     at VersionManager.getTransactionSelector (/ion/node_modules/@decentralized-identity/sidetree/dist/lib/core/VersionManager.js:121:30)
ion-core        |     at ThroughputLimiter.<anonymous> (/ion/node_modules/@decentralized-identity/sidetree/dist/lib/core/ThroughputLimiter.js:36:65)
ion-core        |     at Generator.next (<anonymous>)
ion-core        |     at /ion/node_modules/@decentralized-identity/sidetree/dist/lib/core/ThroughputLimiter.js:7:71
ion-core        |     at new Promise (<anonymous>)
ion-core        |     at __awaiter (/ion/node_modules/@decentralized-identity/sidetree/dist/lib/core/ThroughputLimiter.js:3:12)
ion-core        |     at ThroughputLimiter.getQualifiedTransactions (/ion/node_modules/@decentralized-identity/sidetree/dist/lib/core/ThroughputLimiter.js:23:16)
ion-core        |     at Observer.<anonymous> (/ion/node_modules/@decentralized-identity/sidetree/dist/lib/core/Observer.js:97:78)
ion-core        |     at Generator.next (<anonymous>) code: 'version_manager_version_string_not_found' }
ion-core        | Refreshing cached blockchain time...
ion-core        | Refreshed blockchain time: {"time":1773344,"hash":"00000000000001a2847271cf4fe00df29bce7a2b024f68801c6479ad4229cbec"}
```

Configuration being used is the standard config checked into the repo on the bitcoin test net

**Comment by thehenrytsai** [comment]
This should not repro in v1 ION.
